# Copyright (C) 2025 Roman Maksimov.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# .github/workflows/python_testing.yml

name: Run Quests Tests

# Запускать этот скрипт при каждом push или pull_request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Используем стандартный сервер Linux
    
    steps:
    - uses: actions/checkout@v4 # 1. Клонируем код проекта

    - name: Set up Python 3.x # 2. Устанавливаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Run Quest 1 Tests # 3. Запускаем тесты для первого квеста
      # ВАЖНО: Удаляем working-directory и запускаем тест по полному пути из корня!
      run: python 01_Basics_and_Loops/tests/test_quest_1.py